name: iOS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-ios:
    runs-on: macos-13
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies and sync
        run: |
          npm ci
          npm run build
          npx cap sync ios

      - name: Install pods
        run: |
          cd ios/App
          pod install

      - name: Build iOS
        run: |
          xcodebuild \
            -workspace "ios/App/App.xcworkspace" \
            -scheme "App" \
            -configuration Release \
            -sdk iphoneos \
            -archivePath $PWD/build/App.xcarchive \
            archive

      - name: Export IPA
        run: |
          xcodebuild \
            -exportArchive \
            -archivePath $PWD/build/App.xcarchive \
            -exportOptionsPlist ios/exportOptions.plist \
            -exportPath $PWD/build

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: App-Release-IPA
          path: build/App.ipa 